### PR TITLE
EXPDAT-020 - Icon for App

### LINKED ISSUE #20: EXPDAT-020 icon
# user story

**As a** user

**I want** the app to have an Icon

**so that** I can better find it on my homescreen

# feature criteria
- [x] add the attached png file as app icon
logo

# Acceptance criteria
- [x] runs local without errors
- [x] commit message contains issue abbreviations
- [ ] tests written for it

### PR DESCRIPTION
**Pull request by ChrisFartek**
This closes #20.

### CODE REVIEW

**Comment by bengaal** [comment]
Test: 
image

**Review by steschi — COMMENTED** [review]
@bengaal  any clue why your IDE behaves different concerning .idea files? I am not sure we should change the default bytecodeTargetLevel and am not sure if codeStyle changes are a good idea / needed?

**Comment by bengaal** [comment]
> 
> 
> @bengaal any clue why your IDE behaves different concerning .idea files? I am not sure we should change the default bytecodeTargetLevel and am not sure if codeStyle changes are a good idea / needed?

I have no idea whatsoever. Does it change the behavior of the application?

**Comment by steschi** [comment]
> > @bengaal any clue why your IDE behaves different concerning .idea files? I am not sure we should change the default bytecodeTargetLevel and am not sure if codeStyle changes are a good idea / needed?
> 
> I have no idea whatsoever. Does it change the behavior of the application? At yesterday's session I remember discussing that we do commit .idea files that aren't covered in the .gitignore.

yes, commiting .idea files is ok, I am just wondering why these changes needed to be done. Especially the java version issue could lead to a problem. I wonder why your Android Studio prefers 1.11 over 1.8 and tries to change that.

**Review by steschi — APPROVED** [review]
no failing tests, icon is visible in launcher

**Pull request merged**
